# PSD Normalization Example

This notebook aims to showcase how to normaliza PSD using the functionalities in the repo.

In [2]:
import os

import polars as pl
import numpy as np
import datetime as dt
from datetime import timedelta

from orcasound_noise.utils import Hydrophone, S3FileConnector
from orcasound_noise.analysis.partitioned_accessor import PartitionedAccessor

In [3]:
hydrophone = Hydrophone.ORCASOUND_LAB
os.environ["AWS_PROFILE"] = "ambient-sound-team" ## User will need tokens to access the S3 bucket.

## Method 1: Normalization by a Scalar

In [4]:
# Step 1: Get the reference table 

## Set input time
date = dt.datetime(2026, 3, 9) # target date

## Access the refernce table
file_connector = S3FileConnector(hydrophone)
folder = 'data/temp/'
if not os.path.exists(folder):
    os.makedirs(folder)
ref_file_path = f"{folder}{hydrophone.name}_ref.parquet"

file_connector.get_ref_file(hydrophone, folder)
pl_ref = pl.read_parquet(ref_file_path)
pl_ref.head()

## Get the reference value of the date, we have saved the reference broadband, which calculated based on rolling 7-day 5th percentile of the broadband, in our s3
## Refer to orca-action-workflow repo for more details
bb_ref = pl_ref.filter(pl.col("date") == date).select('bb_ref').item()
bb_ref

-55.695

In [5]:
# Step 2: Get the PSD table
start = dt.datetime.combine(date, dt.time.min)
end = dt.datetime.combine(date, dt.time.max)

## Get the data
accessor = PartitionedAccessor(hydrophone, start, end)
pl_psd, pl_bb = accessor.get_dataframes(lazy=False)
pl_psd.head()

shape: (5, 103)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ ind       ┆ 67        ┆ 71        ┆ 75        ┆ … ┆ 19000     ┆ 20000     ┆ 21200     ┆ 22400    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ datetime[ ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
│ ns]       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 2026-03-0 ┆ -39.15809 ┆ -37.57186 ┆ -38.53383 ┆ … ┆ -57.43396 ┆ -59.57485 ┆ -59.89906 ┆ -59.8749 │
│ 9         ┆ 9         ┆ 6         ┆ 8         ┆   ┆ 1         ┆ 9         ┆ 8         ┆ 74       │
│ 00:00:00  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2026-03-0 ┆ -38.64511 ┆ -38.33926 ┆ -36.73083 ┆ … ┆ -57.17098 ┆ -59.43998 ┆ -59.84451 ┆ -59.8499 │
│ 9         ┆ 9         ┆ 6         ┆ 5         ┆   ┆           ┆ 8         ┆ 4         ┆ 54       │
│ 00:00:01  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2026-03-0 ┆ -37.79475 ┆ -36.36541 ┆ -37.23171 ┆ … ┆ -57.58926 ┆ -59.51476 ┆ -59.86476 ┆ -59.8649 │
│ 9         ┆           ┆ 6         ┆ 9         ┆   ┆ 3         ┆ 7         ┆ 7         ┆ 74       │
│ 00:00:02  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2026-03-0 ┆ -37.25211 ┆ -36.91213 ┆ -37.59462 ┆ … ┆ -57.54884 ┆ -59.55497 ┆ -59.79989 ┆ -59.7997 │
│ 9         ┆ 5         ┆           ┆ 1         ┆   ┆ 9         ┆ 4         ┆ 6         ┆ 12       │
│ 00:00:03  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2026-03-0 ┆ -38.06839 ┆ -38.21689 ┆ -39.80891 ┆ … ┆ -57.50396 ┆ -59.48995 ┆ -59.92998 ┆ -59.8749 │
│ 9         ┆ 5         ┆ 6         ┆ 6         ┆   ┆ 1         ┆ 4         ┆ 8         ┆ 74       │
│ 00:00:04  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [6]:
# Step 3-1: Get the reference value of each frequency band
# Using white noise reference: the power is equally distributed across the entire frequency range (0-24 kHz)
import numpy as np

## Set parameters
total_freq_range = 24000 # Total frequency range
octave_bands = 12 # Number of octave bands

## Transform the reference broadband dB level to the Reference Power Density (Linear)
ref_power_density = (10**(bb_ref / 10)) 
ref_power_density /= total_freq_range

## Get the center frequencies of the octave bands
center_freqs = pl_psd.collect_schema().names()
center_freqs.remove('ind') # Remove timestamp column
center_freqs = np.array([int(freq) for freq in center_freqs])

## Width of a 1/12 octave band:
band_widths = center_freqs * (2**(1/(2*octave_bands)) - 2**(-1/(2*octave_bands)))

## Convert each band's reference to dB
spectral_ref_vector = 10 * np.log10(ref_power_density * band_widths)
spectral_ref_vector

array([-93.6193185 , -93.36748304, -93.12945389, -92.84916666,
       -92.58587727, -92.33764143, -92.10283047, -91.88006653,
       -91.62700788, -91.3878863 , -91.16124645, -90.9109664 ,
       -90.67432722, -90.41878617, -90.11915394, -89.8388667 ,
       -89.57557731, -89.32734148, -89.09253052, -88.86976657,
       -88.61670792, -88.37758634, -88.1509465 , -87.90066644,
       -87.64760779, -87.40848621, -87.10885398, -86.89696099,
       -86.62961846, -86.377783  , -86.13975385, -85.85946661,
       -85.59617723, -85.34794139, -85.11313043, -84.89036648,
       -84.63730783, -84.39818626, -84.09855402, -83.88666103,
       -83.6193185 , -83.36748304, -83.12945389, -82.84916666,
       -82.58587727, -82.33764143, -82.10283047, -81.88006653,
       -81.62700788, -81.3878863 , -81.16124645, -80.9109664 ,
       -80.67432722, -80.41878617, -80.11915394, -79.8388667 ,
       -79.57557731, -79.32734148, -79.09253052, -78.86976657,
       -78.61670792, -78.37758634, -78.1509465 , -77.90066644,
       -77.64760779, -77.40848621, -77.10885398, -76.89696099,
       -76.62961846, -76.377783  , -76.13975385, -75.85946661,
       -75.59617723, -75.34794139, -75.11313043, -74.89036648,
       -74.63730783, -74.39818626, -74.09855402, -73.88666103,
       -73.6193185 , -73.36748304, -73.12945389, -72.84916666,
       -72.58587727, -72.33764143, -72.10283047, -71.88006653,
       -71.62700788, -71.3878863 , -71.16124645, -70.9109664 ,
       -70.67432722, -70.41878617, -70.11915394, -69.8388667 ,
       -69.57557731, -69.32734148, -69.09253052, -68.86976657,
       -68.61670792, -68.37758634])

In [7]:
# Step 4-1: Minus the reference value from the PSD table to get the normalized PSD using white noise reference.
df_normalized = pl_psd.with_columns([
    (pl.col(str(freq)) - spectral_ref_vector[i]).alias(str(freq)) for i, freq in enumerate(center_freqs)
])
df_normalized.head()

shape: (5, 103)
┌─────────────┬───────────┬───────────┬───────────┬───┬───────────┬──────────┬──────────┬──────────┐
│ ind         ┆ 67        ┆ 71        ┆ 75        ┆ … ┆ 19000     ┆ 20000    ┆ 21200    ┆ 22400    │
│ ---         ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---      ┆ ---      ┆ ---      │
│ datetime[ns ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64      ┆ f64      ┆ f64      │
│ ]           ┆           ┆           ┆           ┆   ┆           ┆          ┆          ┆          │
╞═════════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪══════════╪══════════╪══════════╡
│ 2026-03-09  ┆ 54.461219 ┆ 55.795617 ┆ 54.595616 ┆ … ┆ 11.658569 ┆ 9.294908 ┆ 8.71764  ┆ 8.502612 │
│ 00:00:00    ┆           ┆           ┆           ┆   ┆           ┆          ┆          ┆          │
│ 2026-03-09  ┆ 54.974199 ┆ 55.028217 ┆ 56.398619 ┆ … ┆ 11.92155  ┆ 9.429778 ┆ 8.772194 ┆ 8.527632 │
│ 00:00:01    ┆           ┆           ┆           ┆   ┆           ┆          ┆          ┆          │
│ 2026-03-09  ┆ 55.824569 ┆ 57.002067 ┆ 55.897735 ┆ … ┆ 11.503267 ┆ 9.355    ┆ 8.751941 ┆ 8.512612 │
│ 00:00:02    ┆           ┆           ┆           ┆   ┆           ┆          ┆          ┆          │
│ 2026-03-09  ┆ 56.367203 ┆ 56.455353 ┆ 55.534833 ┆ … ┆ 11.543682 ┆ 9.314792 ┆ 8.816812 ┆ 8.577874 │
│ 00:00:03    ┆           ┆           ┆           ┆   ┆           ┆          ┆          ┆          │
│ 2026-03-09  ┆ 55.550923 ┆ 55.150587 ┆ 53.320538 ┆ … ┆ 11.588569 ┆ 9.379813 ┆ 8.686719 ┆ 8.502612 │
│ 00:00:04    ┆           ┆           ┆           ┆   ┆           ┆          ┆          ┆          │
└─────────────┴───────────┴───────────┴───────────┴───┴───────────┴──────────┴──────────┴──────────┘

In [8]:
# Step 3-2: Get the reference value of each frequency band
# Using Pink noise reference: the power is equally distributed across the octave bands

## Set parameters
total_freq_range = 24000 # Total frequency range
octave_bands = 12 # Number of octave bands

## Get the center frequencies of the octave bands
center_freqs = pl_psd.collect_schema().names()
center_freqs.remove('ind') # Remove timestamp column
center_freqs = np.array([int(freq) for freq in center_freqs])

## Convert each band's reference to dB
## ref_per_band = 10 * log_{10}(10**(bb_ref / 10) / N) 
##              = 10 * log_{10}(10**(bb_ref / 10)) - 10 * log_{10}(N) 
##              = bb_ref - 10 * log_{10}(N)
ref_per_band = bb_ref - (10 * np.log10(len(center_freqs)))
ref_per_band

np.float64(-75.78100171761918)

In [9]:
# Step 4-2: Minus the reference value from the PSD table to get the normalized PSD using pink noise reference.
df_normalized = pl_psd.with_columns([
    (pl.col(str(freq)) - ref_per_band).alias(str(freq)) for i, freq in enumerate(center_freqs)
])
df_normalized.head()

shape: (5, 103)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ ind       ┆ 67        ┆ 71        ┆ 75        ┆ … ┆ 19000     ┆ 20000     ┆ 21200     ┆ 22400    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ datetime[ ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
│ ns]       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 2026-03-0 ┆ 36.622903 ┆ 38.209135 ┆ 37.247164 ┆ … ┆ 18.347041 ┆ 16.206143 ┆ 15.881934 ┆ 15.90602 │
│ 9         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 8        │
│ 00:00:00  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2026-03-0 ┆ 37.135883 ┆ 37.441735 ┆ 39.050167 ┆ … ┆ 18.610022 ┆ 16.341013 ┆ 15.936488 ┆ 15.93104 │
│ 9         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 8        │
│ 00:00:01  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2026-03-0 ┆ 37.986252 ┆ 39.415586 ┆ 38.549283 ┆ … ┆ 18.191739 ┆ 16.266235 ┆ 15.916235 ┆ 15.91602 │
│ 9         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 8        │
│ 00:00:02  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2026-03-0 ┆ 38.528886 ┆ 38.868872 ┆ 38.186381 ┆ … ┆ 18.232153 ┆ 16.226028 ┆ 15.981105 ┆ 15.98129 │
│ 9         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 00:00:03  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2026-03-0 ┆ 37.712606 ┆ 37.564106 ┆ 35.972086 ┆ … ┆ 18.277041 ┆ 16.291048 ┆ 15.851013 ┆ 15.90602 │
│ 9         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 8        │
│ 00:00:04  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

## Method 2: Normalization by a Spectrum

In [10]:
# Step 1: Get the PSD table

## Set input time
date = dt.datetime(2026, 3, 9) # target date
start = dt.datetime.combine(date - dt.timedelta(7), dt.time.min) # 2026-03-02
end = dt.datetime.combine(date, dt.time.max) # 2026-03-09

## Get the data
accessor = PartitionedAccessor(hydrophone, start, end)
pl_psd, pl_bb = accessor.get_dataframes(lazy=True)

In [11]:
# Step 2: Calculate the reference value for each center frequency

import numpy as np

## get frequency column names
freqs = pl_psd.collect_schema().names() 
freqs.remove('ind')

## Calculate the reference sound level based on the reference period
## Reference period is 2026-03-02 to 2026-03-08 (7 days before the target date) in this example
ref_start = start
ref_end = dt.datetime.combine(date - dt.timedelta(1), dt.time.max) # 2026-03-08

pl_psd_ref = (
    pl_psd
    .filter(pl.col("ind").is_between(ref_start, ref_end))
    .select(
        pl.all().exclude("ind").quantile(0.05)
    )
).collect()

ref_dict = pl_psd_ref.to_dicts()[0]
ref_dict

{'67': -44.54170455173588,
 '71': -44.71120099038178,
 '75': -44.7689875113923,
 '80': -44.788921936696525,
 '85': -44.77896563591025,
 '90': -44.672308580740335,
 '95': -44.6208931116042,
 '100': -44.545220498140914,
 '106': -44.478054606089295,
 '112': -44.28520196660281,
 '118': -43.76120884135692,
 '125': -43.91347759350728,
 '132': -43.81696277602523,
 '140': -43.7,
 '150': -43.550324816587406,
 '160': -43.37906751977733,
 '170': -43.21968032258457,
 '180': -41.89730052689051,
 '190': -42.769435891076846,
 '200': -42.56485896818967,
 '212': -42.34489760731486,
 '224': -42.115792797442566,
 '236': -41.992221906943634,
 '250': -41.893528049061224,
 '265': -41.75774385732167,
 '280': -41.63943589107684,
 '300': -40.25200256555757,
 '315': -41.52159999873053,
 '335': -41.51568406482393,
 '355': -41.49587392869641,
 '375': -41.55256372492811,
 '400': -41.631605304378326,
 '425': -41.12835106972622,
 '450': -41.811311128853426,
 '475': -41.99016348873009,
 '500': -42.12971218322152,
 '530': -41.526673613885556,
 '560': -42.042995410677406,
 '600': -42.46034236856416,
 '630': -42.51497409596921,
 '670': -42.05018201658781,
 '710': -42.40945371173168,
 '750': -41.95352804906123,
 '800': -41.18153841386583,
 '850': -41.65989638449485,
 '900': -40.72835106972622,
 '950': -41.43730052689051,
 '1000': -40.825655330489894,
 '1060': -40.94926321443669,
 '1120': -40.445684064823936,
 '1180': -40.36476686743094,
 '1250': -38.61222190694363,
 '1320': -39.75485896818967,
 '1400': -39.24290210715685,
 '1500': -39.38186635980456,
 '1600': -39.66399507455867,
 '1700': -39.46834234964558,
 '1800': -39.63451359705817,
 '1900': -39.22822141648077,
 '2000': -39.383201353715094,
 '2120': -39.269435891076846,
 '2240': -39.01958554786731,
 '2360': -38.690123453871685,
 '2500': -39.02360027262927,
 '2650': -38.95705335756323,
 '2800': -39.05131112885342,
 '3000': -39.285893828018075,
 '3150': -39.187743857321664,
 '3350': -38.85186635980456,
 '3550': -39.156727924153294,
 '3750': -39.2644374598783,
 '4000': -38.93476686743094,
 '4250': -39.61485896818967,
 '4500': -39.59492804461324,
 '4750': -39.67290210715685,
 '5000': -39.973477593507276,
 '5300': -40.18373082360644,
 '5600': -39.809953948460915,
 '6000': -39.41971218322152,
 '6300': -39.10995394846092,
 '6700': -39.013477593507275,
 '7100': -38.845684064823935,
 '7500': -39.08476686743094,
 '8000': -39.104858968189674,
 '8500': -39.06396104132914,
 '9000': -38.93391250723403,
 '9500': -38.69251232542374,
 '10000': -38.07926630580412,
 '10600': -37.22834234964559,
 '11200': -37.19050696463996,
 '11800': -38.1832013537151,
 '12500': -39.75981579579689,
 '13200': -41.10860708494191,
 '14000': -42.33161247832822,
 '15000': -43.06591190636447,
 '16000': -43.274997121769275,
 '17000': -43.9658451590376,
 '18000': -52.754766867430945,
 '19000': -59.35995394846092,
 '20000': -60.04485896818967,
 '21200': -60.03995394846092,
 '22400': -59.954974095969206}

In [12]:
# Step 3: Subtract the reference sound level from the PSD of each center band.
pl_psd_normalized = (
    pl_psd
    .filter(pl.col("ind").dt.date() == date.date())
    .with_columns([
        (pl.col(f) - ref_dict[f]).alias(f) 
        for f in freqs
    ])
    .collect()
)

pl_psd_normalized.head()

shape: (5, 103)
┌──────────────┬──────────┬──────────┬──────────┬───┬──────────┬──────────┬──────────┬──────────┐
│ ind          ┆ 67       ┆ 71       ┆ 75       ┆ … ┆ 19000    ┆ 20000    ┆ 21200    ┆ 22400    │
│ ---          ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---      │
│ datetime[ns] ┆ f64      ┆ f64      ┆ f64      ┆   ┆ f64      ┆ f64      ┆ f64      ┆ f64      │
╞══════════════╪══════════╪══════════╪══════════╪═══╪══════════╪══════════╪══════════╪══════════╡
│ 2026-03-09   ┆ 5.383605 ┆ 7.139335 ┆ 6.23515  ┆ … ┆ 1.925993 ┆ 0.47     ┆ 0.140886 ┆ 0.08     │
│ 00:00:00     ┆          ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
│ 2026-03-09   ┆ 5.896585 ┆ 6.371935 ┆ 8.038153 ┆ … ┆ 2.188974 ┆ 0.60487  ┆ 0.19544  ┆ 0.10502  │
│ 00:00:01     ┆          ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
│ 2026-03-09   ┆ 6.746955 ┆ 8.345785 ┆ 7.537269 ┆ … ┆ 1.770691 ┆ 0.530092 ┆ 0.175187 ┆ 0.09     │
│ 00:00:02     ┆          ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
│ 2026-03-09   ┆ 7.289589 ┆ 7.799071 ┆ 7.174367 ┆ … ┆ 1.811105 ┆ 0.489885 ┆ 0.240058 ┆ 0.155262 │
│ 00:00:03     ┆          ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
│ 2026-03-09   ┆ 6.473309 ┆ 6.494305 ┆ 4.960072 ┆ … ┆ 1.855993 ┆ 0.554905 ┆ 0.109965 ┆ 0.08     │
│ 00:00:04     ┆          ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
└──────────────┴──────────┴──────────┴──────────┴───┴──────────┴──────────┴──────────┴──────────┘